### ISSUE TITLE
Standalone Time Picker

### ISSUE THREAD

**Issue by deadghost** [reagent-project/reagent-forms#54] opened 2015-05-09 05:20 UTC
There is currently no time picker field.

Perhaps http://jdewit.github.io/bootstrap-timepicker/ can be used?

**Comment by yogthos** [comment] 2015-05-09 12:23
I'd prefer not to add external js lib dependencies into the core library. A time picker is on the todo list though.

**Comment by yogthos** [comment] 2015-05-10 04:31
duplicate of https://github.com/reagent-project/reagent-forms/issues/37

**Closed by yogthos** 2015-05-10 04:31 UTC
